In [1]:
#Bag of words 

# step 1 : lower all the sentences, removing special characters using re and  removing stop words 
# step 2 : Taking vocubulary, ie unique words and find its frequency. and order it in descending. more repeated word in first. By using "max_features" option in python to select required features.
# step 3 : Creating vector for each sentence but in ohe for each word we create a vector, that is the difference.  


In [2]:
# Eg: 
# s1 : The food is good.
# s2 : The food is not good.
# s3 : The food is good and bad.

# stop words are : the, is , and 
# 1 - food good
# 2 - food not good 
# 3 - food good bad

# unique words: 
# food  good  not  bad 

# food 3 
# good 3
# not 1
# bad 1 

# vector is : 
#             [food,good,not,bad]
# food good  - [1,1,0,0]
# food not  good - [1,1,1,0]
# food bad good - [1,1,0,1]

# 2 types of BOW : 
#   - Binary BOW - vectors only contains 0,1 
#   - Normal BOW  - vectors may contains 0,1,2,3... 

#    Normal BOW Eg : 
#     food good food - [2,1,0,0]


# Advantages of BOW:
# - Easy to implement and intuitive. 
# - fixed size of input but not in ohe. 

# Disadvantages :
# - sparse matrix leads to overfitting if features increases 
# - Ordering of the words is changed. Bcz we are indexing the features based on frequency.
#     [food good not bad ] --> order 
#     S - food bad good -> [1,1,0,1] --> same vector but order of the word is changed. meaning is completely changed.
# - out of vocubulary
# - semantic meaning is not captured.
#    s1 - The food is good 
#    s2 - The food is not good. 
#    unique - The food is good not 
#    s1 - [1,1,1,1,0]
#    s2 - [1,1,1,1,1]
   
#    if we plot the vectors in 3d plane , the distance or angle will be very less by using cosine similarity due to only one point is varied. but the meaning is completely different. 




In [3]:
import pandas as pd
import numpy as np

In [4]:
ds = pd.read_csv('spam.csv',encoding='latin1')
print(ds.iloc[5549])
ds


v1                                                          ham
v2            You know, wot people wear. T shirts, jumpers, ...
Unnamed: 2                                                  NaN
Unnamed: 3                                                  NaN
Unnamed: 4                                                  NaN
Name: 5549, dtype: object


v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [5]:
ds.columns

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

In [6]:
ds.drop(columns=["Unnamed: 2","Unnamed: 3","Unnamed: 4"],inplace=True) # inplace ==> True - no need to reassign the ds , after delete it will affect in ds
ds

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [7]:
ds.head(10)

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
5  spam  FreeMsg Hey there darling it's been 3 week's n...
6   ham  Even my brother is not like to speak with me. ...
7   ham  As per your request 'Melle Melle (Oru Minnamin...
8  spam  WINNER!! As a valued network customer you have...
9  spam  Had your mobile 11 months or more? U R entitle...

In [8]:
import re
import nltk

from nltk.corpus import stopwords

from nltk.stem import WordNetLemmatizer

lemmatiser = WordNetLemmatizer()

nltk.download('all')



[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to
[nltk_data]    |     /home/nextbraingpu2/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     /home/nextbraingpu2/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /home/nextbraingpu2/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     /home/nextbraingpu2/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_eng is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /home/nextbraingpu2/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru

True

In [9]:
stop_words = stopwords.words('english')
stopwords.words()

['tyre',
 'rreth',
 'le',
 'atyre',
 'këta',
 'megjithëse',
 'kemi',
 'per',
 'ndonëse',
 'dytë',
 'pse',
 'tha',
 'aty',
 'ndaj',
 'ke',
 'këtë',
 'duhet',
 'pa',
 'perket',
 'veç',
 'ndonje',
 'një',
 'keshtu',
 's',
 'janë',
 'jane',
 'ti',
 'ia',
 'megjithese',
 'prej',
 'ishte',
 'tjerë',
 'ai',
 'se',
 'tillë',
 'do',
 'si',
 'ja',
 'tonë',
 'keta',
 'pastaj',
 'ndersa',
 'siç',
 'unë',
 'gjate',
 'di',
 'kësaj',
 'cilin',
 'kjo',
 'dhënë',
 'da',
 'teper',
 'ketij',
 'ama',
 'pasi',
 'fjalë',
 'kanë',
 'vetem',
 'za',
 'd.m.th.',
 'ose',
 'pas',
 'ndonjë',
 'cila',
 'ndodhur',
 'dyte',
 'ardhur',
 'kësi',
 'nga',
 'vete',
 'atij',
 'ta',
 'jenë',
 'rendit',
 'tane',
 'keso',
 'deri',
 'tone',
 'të',
 'prandaj',
 'bëjë',
 'domethënë',
 'dhe',
 'qi',
 'mirepo',
 'tona',
 'që',
 'u',
 'këtu',
 'cilet',
 'jene',
 'tjere',
 'gjë',
 'së',
 'gjatë',
 'duhej',
 't',
 'dhene',
 'thuhet',
 'po',
 'une',
 'dy',
 'cfare',
 'ndërsa',
 'sepse',
 'edhe',
 'cilen',
 'to',
 'meqenese',
 'meje',


In [10]:
ds_message = ds["v2"]
ds_label = ds["v1"]
print (ds_message)
print (ds_label)

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: v2, Length: 5572, dtype: object
0        ham
1        ham
2       spam
3        ham
4        ham
        ... 
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: v1, Length: 5572, dtype: object


In [ ]:


for i in range(len(ds_message)):
    
    sentence = ds_message[i]
    s = re.sub("[^A-Za-z0-9]"," ",sentence)
    ss = s.lower().split()
    word = [lemmatiser.lemmatize(word,pos='v') for word in ss if word not in stopwords.words() ]
    w1 = " ".join(word)
    ds_message[i] = w1


ds_message
   

0       jurong point crazy available bugis great world...
1                                            lar joke wif
2       free entry 2 wkly comp win cup final tkts 21st...
3                                               dun early
4                                                usf live
                              ...                        
5567    2nd time 2 contact 750 pound prize 2 claim eas...
5568                                  b esplanade fr home
5569                                pity mood suggestions
5570            guy bitch act interest buy week give free
5571                                                 rofl
Name: v2, Length: 5572, dtype: object

In [ ]:
New_dataframe = pd.concat([ds_message,ds_label],axis=True)
New_dataframe.rename(columns={'v1': 'labels', 'v2': 'messages'},inplace=True)
New_dataframe

messages labels
0     jurong point crazy available bugis great world...    ham
1                                          lar joke wif    ham
2     free entry 2 wkly comp win cup final tkts 21st...   spam
3                                             dun early    ham
4                                              usf live    ham
...                                                 ...    ...
5567  2nd time 2 contact 750 pound prize 2 claim eas...   spam
5568                                b esplanade fr home    ham
5569                              pity mood suggestions    ham
5570          guy bitch act interest buy week give free    ham
5571                                               rofl    ham

[5572 rows x 2 columns]

In [94]:
### Create Bag of words
# sklearn for Bag of words 
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1000,binary=True,ngram_range=(2,2)) #binary ==> if true frequency will be a one or zero if false its frequency
a = cv.fit_transform(New_dataframe['messages']).toarray()
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5572, 1000))

In [ ]:
# important parameters used in CountVectoriser 

# max features = Most repeated vocubulary as features
# binary =if true frequency will be a one or zero if false its frequency
# ngrams = bigrams, trigrams (combining 2 or 3 consecutive words )
# stopwords 


In [95]:
cv.vocabulary_

{'free entry': np.int64(358),
 'wkly comp': np.int64(976),
 'cup final': np.int64(281),
 'std txt': np.int64(797),
 'txt rate': np.int64(874),
 'rate apply': np.int64(697),
 'set callertune': np.int64(755),
 'callertune callers': np.int64(190),
 'callers press': np.int64(189),
 'press copy': np.int64(680),
 'copy friends': np.int64(264),
 'friends callertune': np.int64(374),
 '900 prize': np.int64(111),
 'claim call': np.int64(220),
 'claim code': np.int64(221),
 'mobile 11': np.int64(577),
 'entitle update': np.int64(324),
 'update latest': np.int64(887),
 'latest colour': np.int64(495),
 'free call': np.int64(355),
 'call mobile': np.int64(182),
 'mobile update': np.int64(586),
 'update co': np.int64(886),
 'co free': np.int64(233),
 'chance win': np.int64(208),
 'cash 100': np.int64(197),
 'cost 150p': np.int64(267),
 'reply hl': np.int64(717),
 'week free': np.int64(951),
 '000 prize': np.int64(4),
 'txt word': np.int64(876),
 'mobile charge': np.int64(581),
 'great weekend': np.in

In [87]:
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5572, 2500))

In [88]:
a[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(2500,))

In [41]:
print(len(cv.get_feature_names_out()))

1000


In [44]:
word_counts = np.sum(a, axis=0)
word_counts

array([ 10,  29,   8,  13,  12,   8,  13,  15,  16,   8,   8,  41,  41,
        41,  24,  17,   9,  12,  17,  18,  71,  34,  52,  51,  38,  12,
        12,  25,  13,   8,   9,   7,  18,   8,   9,  15,  30,  10,  15,
         8,  15,   7,   7,   7,   9,  61,  44,  25,   8,   7,   8,  19,
         7,  22,  21,   7,   7,  19,  13,   8,  10,  11,  26,  12,   9,
         9,  43,  16,  22,  10,   7,  19,  28,  19,   9,  13,   8,   7,
        33,   8,  24,   7,  86,  18,  32,   8,  16,   8,  34,   9,  22,
        13,   7,   8,  11,  33,  12,  13,  24,  18,  18,   8,  28,   7,
        67,  25,  19,  14,  79,  33, 153,  10,   8,  13,  17,  15,  10,
         7,   9,  11,   8,  21,  32,   8,   7,  21,   9,  37,  16,   7,
        36,  47,   8,   7,  11,  14,   9,   7,  21,  39,  28,   9,   8,
        15,  35,  32,  16,  26,  43,  20,  13,  34,   7,   7,  31,  21,
        82,   7,   7,   9,   7, 677,  12,  13,  10,  15,  38,  11,  41,
        18,   7,  17,  15,  89,  16,   9,   7,  41,  33,   7,  3

In [43]:
word_counts = np.sum(a, axis=0)
word_counts.sort()
word_counts

array([  7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,
         7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,
         7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,
         7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,
         7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,
         7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,
         7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,
         7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,
         7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,   7,
         7,   7,   7,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,
         8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,
         8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,
         8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,
         8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   